CREATE TABLE CAD_UF (
  DS_UF CHAR(2) NOT NULL,
  NM_UF VARCHAR(60),
  PRIMARY KEY(DS_UF)
);

CREATE TABLE PECAS (
  CD_PECA INTEGER NOT NULL,
  DS_PECA VARCHAR(60),
  PRIMARY KEY(CD_PECA)
);

CREATE TABLE SERVICO (
  CD_SERVICO INTEGER NOT NULL,
  DS_SERVICO VARCHAR(60),
  VL_SERVICO NUMERIC(8,2),
  PRIMARY KEY(CD_SERVICO)
);

CREATE TABLE CAD_CIDADE (
  CD_CIDADE INTEGER NOT NULL,
  DS_UF CHAR(2) NOT NULL,
  DS_CIDADE VARCHAR(60),
  PRIMARY KEY(CD_CIDADE),
  FOREIGN KEY(DS_UF) REFERENCES CAD_UF(DS_UF));

CREATE TABLE CAD_ENDERECO (
  CD_ENDERECO INTEGER NOT NULL,
  CD_CIDADE INTEGER NOT NULL,
  DS_ENDERECO VARCHAR(60),
  PRIMARY KEY(CD_ENDERECO),
  FOREIGN KEY(CD_CIDADE) REFERENCES CAD_CIDADE(CD_CIDADE));

CREATE TABLE CAD_PESSOA (
  CD_PESSOA INTEGER NOT NULL,
  CD_ENDERECO INTEGER NOT NULL,
  DS_PESSOA VARCHAR(60),
  DS_SEXO CHAR(2),
  IN_SITUACAO CHAR(2),
  DT_CADASTRO DATE,
  PRIMARY KEY(CD_PESSOA),
  FOREIGN KEY(CD_ENDERECO) REFERENCES CAD_ENDERECO(CD_ENDERECO));

CREATE TABLE ORDEM_SERVICO (
  CD_ORDEM INTEGER NOT NULL,
  CD_PESSOA INTEGER NOT NULL,
  DT_ORDEM DATE,
  VL_ORDEM NUMERIC(8,2),
  PRIMARY KEY(CD_ORDEM),
  FOREIGN KEY(CD_PESSOA) REFERENCES CAD_PESSOA(CD_PESSOA));

CREATE TABLE OS_SERVICO (
  CD_SERVICO INTEGER NOT NULL,
  CD_ORDEM INTEGER NOT NULL,
  QT_HORAS NUMERIC(7,2),
  VL_HORAS NUMERIC(7,2),
  PRIMARY KEY(CD_SERVICO, CD_ORDEM),
  FOREIGN KEY(CD_ORDEM)   REFERENCES ORDEM_SERVICO(CD_ORDEM),
  FOREIGN KEY(CD_SERVICO) REFERENCES SERVICO(CD_SERVICO));

CREATE TABLE OS_SERVICO_PECAS (
  CD_PECA INTEGER NOT NULL,
  CD_ORDEM INTEGER NOT NULL,
  CD_SERVICO INTEGER NOT NULL,
  QT_PECA NUMERIC(8,2),
  VL_PECA NUMERIC(8,2),
  PRIMARY KEY(CD_PECA, CD_ORDEM, CD_SERVICO),
  FOREIGN KEY(CD_SERVICO, CD_ORDEM) REFERENCES OS_SERVICO(CD_SERVICO, CD_ORDEM),
  FOREIGN KEY(CD_PECA) REFERENCES PECAS(CD_PECA));

